apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "network_exporter.labels" . | nindent 4 }}
  name: {{ include "network_exporter.fullname" . }}
data:
  config.yml: |
{{ toYaml .Values.config | indent 4 }}